/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.jparestresource.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.*;

/**
 * @author andrew
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class User implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    @Basic
    private String displayName;

    @OneToMany(mappedBy = "user")
    @XmlTransient
    private List<Document> documents;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public List<Document> getDocuments() {
        if (documents == null) {
            documents = new ArrayList<>();
        }
        return documents;
    }

    public void setDocuments(List<Document> documents) {
        this.documents = documents;
    }

    public void addDocument(Document document) {
        getDocuments().add(document);
        document.setUser(this);
    }

    public void removeDocument(Document document) {
        getDocuments().remove(document);
        document.setUser(null);
    }

}